### ISSUE TITLE
A question on the non-existent mesh

### ISSUE THREAD

**Issue by wzm2256** [Wuziyi616/multi_part_assembly#13]
Hi, I have a minor question on the loading of the BB dataset.

I saw a few warning that the mesh does not exist. I am curious whether that is normal or something goes wrong?

https://github.com/Wuziyi616/multi_part_assembly/blob/224d922485a85059d1094a24e48956e4bf7868cd/multi_part_assembly/datasets/geometry_data.py#L61

**Comment by Wuziyi616** [comment]
Yes, I think that's normal. The mesh dir are generated before we apply the breaking simulation, and we cannot generate fractures for some meshes (e.g. due to low quality, or some corner cases in the simulation algorithm)
