### ISSUE TITLE
A question on duplicated data in BB dataset

### ISSUE THREAD

**Issue by wzm2256** [Wuziyi616/multi_part_assembly#14]
I notice that some point clouds are extremly similar or even completely the same when I scan the dataset. My question is why does that happen?

For example, I try to get all samples with $2$ parts in Bowl class
``
BB_data = GeometryPartDataset(category='Bowl', num_points=10000, min_num_part=2,  max_num_part=2, data_dir='dir', data_fn='data_split/everyday.train.txt', data_keys=('part_ids', ),)
``
but the 0-th data is almost the same as the 1-st data
![1699286778904](https://github.com/Wuziyi616/multi_part_assembly/assets/24223188/1d244c2d-1f32-4ffe-92a2-606ca3fcaeba)

![1699286801919](https://github.com/Wuziyi616/multi_part_assembly/assets/24223188/28f52cea-dae2-4878-8321-383a51124ce1)

The first image is the 0-th data, and the second image is the 1-st data.

That actually happens quite frequently - I estimate that almost 2/3 of the data in this case is duplicated. I am wondering whether it is possible to get rid the duplicated data.

PS: I remove the recentering and random rotation augmentation in the `__get_item` function
```
            # pc, gt_trans = self._recenter_pc(pc)
            # pc, gt_quat = self._rotate_pc(pc)
```

**Comment by Wuziyi616** [comment]
We indeed observed a few cases like this. However, they are not duplicates -- the geometry of these meshes has some very small differences (it is hard to tell these minor differences from the point cloud as it somewhat blurs the cutting interface), and thus it's hard to de-duplicate them. Also, I guess such issues are much less frequent in the more-part cases, because the fracturing pattern is much more diverse.

**Comment by wzm2256** [comment]
> We indeed observed a few cases like this. However, they are not duplicates -- the geometry of these meshes has some very small differences (it is hard to tell these minor differences from the point cloud as it somewhat blurs the cutting interface), and thus it's hard to de-duplicate them. Also, I guess such issues are much less frequent in the more-part cases, because the fracturing pattern is much more diverse.

That is not 'a few' cases. As I said, most of the data are highly similar, if not duplicated, at least in the 2 parts case. This should be noted in the dataset for clarification. Anyway, since you have already close this issue, I won't complain about this further.

**Comment by Wuziyi616** [comment]
I said "a few" meaning it doesn't happen a lot in the entire dataset. Indeed, the 2-part data may have many such issues as 2 is so limited in the way it fractured. I'm not the geometry simulation person in the project, so I cannot comment more on this issue.
