### ISSUE TITLE
Volume constrained data

### ISSUE THREAD

**Issue by eric-zqwang** [Wuziyi616/multi_part_assembly#16]
Hi, 

I have a question related to the new data with feature volume constrained. I wonder for the volume constrained data, does it just simply delete the data which have small pieces in the datase Or re-simulated data. Does it have same data split with the original data?

**Comment by Wuziyi616** [comment]
If I remember correctly, we re-simulated the data with a rejection sampling method, so it is not a subset of the previous non-constrained data.

**Comment by eric-zqwang** [comment]
Great Thanks. 

One more thing I want to clarify. Does it use same data split in the training data and val data for the object between non-constrained and volume constrained? 

I mean is there any possible that the non-constrained training data can be found in volume-constrained test data

**Comment by Wuziyi616** [comment]
I believe so, the data split should be the same. You can check with the split file to see if there is overlap in the object ID.
