### ISSUE TITLE
A mistake in usage.md

### ISSUE THREAD

**Issue by ronaldpan** [Wuziyi616/multi_part_assembly#18]
python scrips/vis.py --cfg_file $CFG --weight path/to/weight --category $CATEGORY --vis $NUM_TO_SAVE

should be 

python scripts/vis.py --cfg_file $CFG --weight path/to/weight --category $CATEGORY --vis $NUM_TO_SAVE

**Comment by Wuziyi616** [comment]
Ah.. Thanks so much for catching this. Do you mind creating a PR to fix it? There is another place in `usage.md` where I wrote the typo `scrips`. Would be great if you can fix both.

**Comment by Wuziyi616** [comment]
Fixed in #19
