### ISSUE TITLE
The 'info file' for splitting train/val list in trivial training 

### ISSUE THREAD

**Issue by xuqunce** [Wuziyi616/multi_part_assembly#2]
Hi, thanks for the great work and dataset.

I tried to use these codes to start my training progress, but it proposed an error related to the 
_C.data_fn = everyday.train.txt (for default)
like 'No such file or directory: './everyday/everyday.train.txt'

I have checked the _split_data.py_ and found that it needs the parameter '--info_file' as an augment.
However, there are no details about the format or data structure of the contents in the 'info_file' either in [https://github.com/Breaking-Bad-Dataset/Breaking-Bad-Dataset.github.io](url) 

It would be appreciated if you could provide an example or instruction about generating the info_file for input.

Thanks a lot!

**Comment by Wuziyi616** [comment]
Hi, thank you for your interest in our work. For the data split file, you don't need to generate it by yourself, and we have uploaded it to the online dataset repo as well. As can be seen in the following screenshot. All you need to do is put it under `./data/breaking_bad/xxx.txt`

![图片](https://user-images.githubusercontent.com/37072215/196482241-1956a1f8-e154-4830-9025-f1ced31e4867.png)

The `split_data.py` is just a reference for you in case you want to generate your own data, and create your own data splits in the future.

**Comment by xuqunce** [comment]
> Hi, thank you for your interest in our work. For the data split file, you don't need to generate it by yourself, and we have uploaded it to the online dataset repo as well. As can be seen in the following screenshot. All you need to do is put it under `./data/breaking_bad/xxx.txt`
> 
> ![图片](https://user-images.githubusercontent.com/37072215/196482241-1956a1f8-e154-4830-9025-f1ced31e4867.png)
> 
> The `split_data.py` is just a reference for you in case you want to generate your own data, and create your own data splits in the future.

Thanks for your reply! :) I indeed ignored that files when I downloaded the dataset...
